export const data = [
  {
    id: '1',
    tag: '1 resolution',
    header: 'employee queries resolved automatically',
    text: 'AI-powered helpdesk understands your employees’ native languages and gives accurate resolutions without any human interference.',
  },
  {
    id: '2',
    tag: '2 Employee Turnover',
    header: 'employee attrition predicted',
    text: 'The employee engagement platform helps you retain top talent by predicting attrition beforehand.',
  },
  {
    id: '3',
    tag: '3 Case Assignment',
    header: 'employee cases assigned accurately',
    text: 'Leena AI automatically assigns employee tickets to the right people and department.',
  },
  {
    id: '4',
    tag: ' 4 Employee Turnover',
    header: 'employee attrition predicted',
    text: 'The employee engagement platform helps you retain top talent by predicting attrition beforehand.',
  },
  {
    id: '5',
    tag: '5 Case Assignment',
    header: 'employee cases assigned accurately',
    text: 'Leena AI automatically assigns employee tickets to the right people and department.',
  },
  {
    id: '6',
    tag: '6 Case Assignment',
    header: 'employee cases assigned accurately',
    text: 'Leena AI automatically assigns employee tickets to the right people and department.',
  },
  {
    id: '7',
    tag: '7 Employee Turnover',
    header: 'employee attrition predicted',
    text: 'The employee engagement platform helps you retain top talent by predicting attrition beforehand.',
  },
  {
    id: '8',
    tag: '8 Case Assignment',
    header: 'employee cases assigned accurately',
    text: 'Leena AI automatically assigns employee tickets to the right people and department.',
  },
  {
    id: '9',
    tag: '9 Case Assignment',
    header: 'employee cases assigned accurately',
    text: 'Leena AI automatically assigns employee tickets to the right people and department.',
  },
  {
    id: '10',
    tag: '10 resolution',
    header: 'employee queries resolved automatically',
    text: 'AI-powered helpdesk understands your employees’ native languages and gives accurate resolutions without any human interference.',
  },
  {
    id: '11',
    tag: '11 resolution',
    header: 'employee queries resolved automatically',
    text: 'AI-powered helpdesk understands your employees’ native languages and gives accurate resolutions without any human interference.',
  },
  {
    id: '12',
    tag: '12 Employee Turnover',
    header: 'employee attrition predicted',
    text: 'The employee engagement platform helps you retain top talent by predicting attrition beforehand.',
  },
  {
    id: '13',
    tag: '13 Case Assignment',
    header: 'employee cases assigned accurately',
    text: 'Leena AI automatically assigns employee tickets to the right people and department.',
  },
  {
    id: '14',
    tag: '14 Employee Turnover',
    header: 'employee attrition predicted',
    text: 'The employee engagement platform helps you retain top talent by predicting attrition beforehand.',
  },
  {
    id: '15',
    tag: '15 Case Assignment',
    header: 'employee cases assigned accurately',
    text: 'Leena AI automatically assigns employee tickets to the right people and department.',
  },
  {
    id: '16',
    tag: '16 Case Assignment',
    header: 'employee cases assigned accurately',
    text: 'Leena AI automatically assigns employee tickets to the right people and department.',
  },
  {
    id: '17',
    tag: '17 Employee Turnover',
    header: 'employee attrition predicted',
    text: 'The employee engagement platform helps you retain top talent by predicting attrition beforehand.',
  },
  {
    id: '18',
    tag: '18 Case Assignment',
    header: 'employee cases assigned accurately',
    text: 'Leena AI automatically assigns employee tickets to the right people and department.',
  },
  {
    id: '19',
    tag: '19 Case Assignment',
    header: 'employee cases assigned accurately',
    text: 'Leena AI automatically assigns employee tickets to the right people and department.',
  },
];
